_base_: "eval.yml"

data:
  batch_size: 256
  pin_memory: true
  num_workers: 6
  seed: ${train.seed}
  dataset:
    meta:
      gcc3m:
        type: img_txt_pair
        path: ./data/gcc3m
        prefix: '{00000..00331}.tar'
        length: 2798155
      gcc12m:
        type: img_txt_pair
        path: ./data/gcc12m
        prefix: '{00000..01242}.tar'
        length: 9430392
      imagenet:
        type: img_cls_pair
        path: ./data/imagenet
        prefix: imagenet-val-{000000..000049}.tar
        length: 50000
    train:
      - gcc3m
      - gcc12m
    val:
      - imagenet

  img_aug:
    deit_aug: true
    img_size: 224
    img_scale: [0.08, 1.0]
    interpolation: bilinear
    color_jitter: 0.4
    auto_augment: 'rand-m9-mstd0.5-inc1'
    re_prob: 0.25
    re_mode: 'pixel'
    re_count: 1
  text_aug: null

train:
  start_step: 0
  total_steps: 50000
  warmup_steps: 500
  ust_steps: 0
  base_lr: 4e-5
  weight_decay: 0.2
  min_lr: 1e-6
  clip_grad: 5.0
  fp16: true
  fp16_comm: true # use fp16 grad compression for multi-node training
  seed: 0

  lr_scheduler:
    name: cosine

  optimizer:
    name: adamw
    eps: 1e-8
    betas: [0.9, 0.999]


evaluate:
  pamr: false
  kp_w: 0.0
  bg_thresh: 0.5

  save_logits: null

  eval_only: false
  eval_freq: 5000
  template: simple
  task:
    - voc
    - voc20
    - context
    - context59
    - coco_stuff
    - coco_object
    - cityscapes
    - ade20k


checkpoint:
  resume: ''
  save_topk: 3
  save_all: false  # if true, save every evaluation step


model_name: "default"  # display name in the logger
output: ???
tag: "default"
print_freq: 50
seed: 0
wandb: true
